### ISSUE TITLE
VerifyNCName exception

### ISSUE THREAD

**Issue by ghost** [quamotion/androidxmldotnet#14]
Hullo,

On some applications, we get the following stacktrace:
```
System.ArgumentNullException: The empty string '' is not a valid local name. (Parameter 'name')
   at System.Xml.XmlConvert.VerifyNCName(String name, ExceptionType exceptionType)
   at System.Xml.XmlConvert.VerifyNCName(String name)
   at System.Xml.Linq.XName..ctor(XNamespace ns, String localName)
   at System.Xml.Linq.XNamespace.GetName(String localName, Int32 index, Int32 count)
   at System.Xml.Linq.XNamespace.GetName(String localName)
   at System.Xml.Linq.XContainer.ContentReader.ReadContentFrom(XContainer rootContainer, XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(XmlReader reader)
```

Unfortunately it seems this is hard to debug as the stacktrace only shows XmlReader code. Example package to cause the issue is "com.verisign.mvip.main" (E65390ED3765DAA57954C4CCEC6DE450) 
[crash.zip](https://github.com/quamotion/androidxmldotnet/files/3500095/crash.zip).

APKTool shows [Fatal Error] :2:90: Attribute "android:" was already specified for element "manifest"., but it is able to decode the file. AAPT from google (aapt dump xmltree crash.zip AndroidManifest.xml) seems to be fine.

It seems to potentially be an issue with manifest to be containing both `android:compileSdkVersionCodename="9"` and `android:compileSdkVersion="28"` in the manifest tag attributes.

**Comment by ghost** [comment]
It seems that updating the Values/public.xml file with https://android.googlesource.com/platform/frameworks/base/+/master/core/res/res/values/public.xml has fixed the issue

**Comment by qmfrederik** [comment]
Thanks for reporting this! I've pushed a new version, 1.1.7, which includes an updated copy of public.xml.

**Comment by ghost** [comment]
@qmfrederik it appears that the public.xml has updated once again (android-29), is there an option to perhaps provide the public.xml to the tool, as opposed to needing nuget updates?

**Comment by qmfrederik** [comment]
@tick-rick See #18
